// Package embed holds the compressed data files baked into the binary at build time.
// The .gz files are generated by cli/scripts/prepare-data.sh and must exist before
// `go build`. CI runs the script automatically; for local builds run it manually.
package embed

import _ "embed"

// Metadata is the gzipped metadata.json (event summaries, geo, topics, links).
//
//go:embed metadata.json.gz
var Metadata []byte

// Embeddings is the gzipped flat float32 embeddings.bin (N×384 row-major).
//
//go:embed embeddings.bin.gz
var Embeddings []byte

// Schema is the gzipped schema.json (index metadata).
//
//go:embed schema.json.gz
var Schema []byte

// ByTopic is the gzipped by-topic.json index.
//
//go:embed by-topic.json.gz
var ByTopic []byte

// ByLocation is the gzipped by-location.json index.
//
//go:embed by-location.json.gz
var ByLocation []byte

// BySource is the gzipped by-source.json index.
//
//go:embed by-source.json.gz
var BySource []byte

// Events is the gzipped concatenated JSONL of all events (full content).
//
//go:embed events.jsonl.gz
var Events []byte
